config/routes.rb
Rails.application.routes.draw do
  resources :albums
  get 'welcome/index'
  devise_for :users
  resources :artist_list, only: %i[index show]

  root to: 'welcome#index'
end

app/models/album.rb
class Album < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: { user: 0, admin: 1 }
end

app/controllers/albums_controller.rb
class AlbumsController < ProtectedController
  before_action :set_album, only: [:show, :edit, :update, :destroy]
  before_action :set_artists, only: [:new, :edit]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    if current_user.admin?
      @album.destroy
      respond_to do |format|
        format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to albums_url, notice: 'You do not have permisson to delete albums' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:artist, :name, :year)
    end

    def set_artists
      @artists = Artists::RetrieveService.get
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :username, :role])
  end

  def after_sign_in_path_for(resource)
    artist_list_index_path
  end
end

app/controllers/artist_list_controller.rb
require 'open-uri'
require 'json'

class ArtistListController < ProtectedController
  before_action :set_artists, only: [:index, :show]

  def index; end

  def show
    @albums = Album.where(artist: params[:id])
  end

  private

  def set_artists
    @artists = Artists::RetrieveService.get
  end
end

app/controllers/protected_controller.rb
class ProtectedController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artist_list_helper.rb
module ArtistListHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/albums/_form.html.erb
<%= form_with(model: album, local: true) do |form| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
        <% album.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :artist %>
    <%= form.select :artist, @artists, prompt: true %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.date_select :year, discard_day: true, discard_month: true, start_year: 1900, end_year: Date.today.year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Albums</h1>

<table>
  <thead>
    <tr>
      <th>Artist</th>
      <th>Name</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.artist %></td>
        <td><%= album.name %></td>
        <td><%= album.year %></td>
        <td><%= link_to 'Show', album %></td>
        <td><%= link_to 'Edit', edit_album_path(album) %></td>
        <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Artist:</strong>
  <%= @album.artist %>
</p>

<p>
  <strong>Name:</strong>
  <%= @album.name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @album.year %>
</p>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

app/views/artist_list/index.html.erb
<%= render 'artist_list/shared/artist_list' %>

app/views/artist_list/shared/_artist_list.html.erb
<% content_for :head do %>
  <%= javascript_pack_tag 'artists_change' %>
<% end %>

<p id="notice"><%= notice %></p>

<h1 class='artist-list-title'>ArtistList</h1>

<%= form_with(url: '#', id: 'form-artists') do %>
  <div class="field">
    <%= label_tag :artists %>
    <%= select_tag :artists, options_for_select(@artists, params[:id]) ,include_blank: true %>
  </div>
<% end %>

<% unless @albums.blank? %>
  <% @albums.each do |album| %>
    <div class='results'>
      <ul>
        <li><%= album.artist %></li>
        <li><%= album.name %></li>
        <li><%= album.year %></li>
      </ul>
    </div>
  <% end %>
<% else %>
  <div class='results'>
    <ul>
      <li>No results <%= "for <strong>#{params[:id]}</strong>".html_safe if params[:id] %></li>
    </ul>
  </div>
<% end %>

app/views/artist_list/show.html.erb
<%= render 'artist_list/shared/artist_list' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicCollectionApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <%= yield :head %>
  </head>

  <body class="container">
    <% unless controller_name == 'welcome' %>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <%= link_to 'Music Collection App', root_path, class:"navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <% unless controller_name == 'registrations' || controller_name == 'sessions' %>
            <ul class="navbar-nav">
              <li class="nav-item active"><%= link_to 'Albums', albums_path, class:"nav-link" %></li>
              <li class="nav-item active"><%= link_to 'Artists List', artist_list_index_path, class:"nav-link" %></li>
              <li class="nav-item active"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %></li>
            </ul>
          <% end %>
        </div>
      </nav>
      <div class="row"></div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Music Collection App</h1>
  <hr class="my-4">
  <p>
    <%= link_to 'Register', new_user_registration_path, class:"btn btn-primary btn-lg", role: 'button' %>
    <%= link_to 'Sign In', new_user_session_path, class:"btn btn-primary btn-lg", role: 'button'  %>
  </p>
</div>